// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MLMARKML.Model
{
    public class ModelInput
    {
        [ColumnName("SeasonYear"), LoadColumn(0)]
        public float SeasonYear { get; set; }


        [ColumnName("SequenceNumber"), LoadColumn(1)]
        public float SequenceNumber { get; set; }


        [ColumnName("CircuitId"), LoadColumn(2)]
        public float CircuitId { get; set; }


        [ColumnName("DriverId"), LoadColumn(3)]
        public float DriverId { get; set; }


        [ColumnName("LapNumber"), LoadColumn(4)]
        public float LapNumber { get; set; }


        [ColumnName("CurrentPosition"), LoadColumn(5)]
        public float CurrentPosition { get; set; }


        [ColumnName("Milliseconds"), LoadColumn(6)]
        public float Milliseconds { get; set; }


    }
}
