//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Importer.xml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    [System.Xml.Serialization.XmlRootAttribute("MRData", Namespace="http://ergast.com/mrd/1.4", IsNullable=false)]
    public partial class MRDataType {
        
        private SeasonTableType seasonTableField;
        
        private RaceTableType raceTableField;
        
        private StandingsTableType standingsTableField;
        
        private DriverTableType driverTableField;
        
        private ConstructorTableType constructorTableField;
        
        private CircuitTableType circuitTableField;
        
        private StatusTableType statusTableField;
        
        private string seriesField;
        
        private string urlField;
        
        private string limitField;
        
        private string offsetField;
        
        private string totalField;
        
        /// <remarks/>
        public SeasonTableType SeasonTable {
            get {
                return this.seasonTableField;
            }
            set {
                this.seasonTableField = value;
            }
        }
        
        /// <remarks/>
        public RaceTableType RaceTable {
            get {
                return this.raceTableField;
            }
            set {
                this.raceTableField = value;
            }
        }
        
        /// <remarks/>
        public StandingsTableType StandingsTable {
            get {
                return this.standingsTableField;
            }
            set {
                this.standingsTableField = value;
            }
        }
        
        /// <remarks/>
        public DriverTableType DriverTable {
            get {
                return this.driverTableField;
            }
            set {
                this.driverTableField = value;
            }
        }
        
        /// <remarks/>
        public ConstructorTableType ConstructorTable {
            get {
                return this.constructorTableField;
            }
            set {
                this.constructorTableField = value;
            }
        }
        
        /// <remarks/>
        public CircuitTableType CircuitTable {
            get {
                return this.circuitTableField;
            }
            set {
                this.circuitTableField = value;
            }
        }
        
        /// <remarks/>
        public StatusTableType StatusTable {
            get {
                return this.statusTableField;
            }
            set {
                this.statusTableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string series {
            get {
                return this.seriesField;
            }
            set {
                this.seriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class SeasonTableType : TableType {
        
        private SeasonType[] seasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Season")]
        public SeasonType[] Season {
            get {
                return this.seasonField;
            }
            set {
                this.seasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class SeasonType {
        
        private string urlField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class ConstructorStandingType {
        
        private object itemField;
        
        private string positionField;
        
        private float pointsField;
        
        private string winsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Constructor", typeof(ConstructorType))]
        [System.Xml.Serialization.XmlElementAttribute("ConstructorIdRef", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float points {
            get {
                return this.pointsField;
            }
            set {
                this.pointsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string wins {
            get {
                return this.winsField;
            }
            set {
                this.winsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class ConstructorType {
        
        private string nameField;
        
        private string nationalityField;
        
        private string constructorIdField;
        
        private string urlField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string constructorId {
            get {
                return this.constructorIdField;
            }
            set {
                this.constructorIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class DriverStandingType {
        
        private object itemField;
        
        private object[] itemsField;
        
        private string positionField;
        
        private float pointsField;
        
        private string winsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Driver", typeof(DriverType))]
        [System.Xml.Serialization.XmlElementAttribute("DriverIdRef", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Constructor", typeof(ConstructorType))]
        [System.Xml.Serialization.XmlElementAttribute("ConstructorIdRef", typeof(string))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float points {
            get {
                return this.pointsField;
            }
            set {
                this.pointsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string wins {
            get {
                return this.winsField;
            }
            set {
                this.winsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class DriverType {
        
        private string permanentNumberField;
        
        private string givenNameField;
        
        private string familyNameField;
        
        private System.DateTime dateOfBirthField;
        
        private bool dateOfBirthFieldSpecified;
        
        private string nationalityField;
        
        private string driverIdField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string PermanentNumber {
            get {
                return this.permanentNumberField;
            }
            set {
                this.permanentNumberField = value;
            }
        }
        
        /// <remarks/>
        public string GivenName {
            get {
                return this.givenNameField;
            }
            set {
                this.givenNameField = value;
            }
        }
        
        /// <remarks/>
        public string FamilyName {
            get {
                return this.familyNameField;
            }
            set {
                this.familyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateOfBirthSpecified {
            get {
                return this.dateOfBirthFieldSpecified;
            }
            set {
                this.dateOfBirthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string driverId {
            get {
                return this.driverIdField;
            }
            set {
                this.driverIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class StandingsListType {
        
        private DriverStandingType[] driverStandingField;
        
        private ConstructorStandingType[] constructorStandingField;
        
        private string seasonField;
        
        private string roundField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DriverStanding")]
        public DriverStandingType[] DriverStanding {
            get {
                return this.driverStandingField;
            }
            set {
                this.driverStandingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConstructorStanding")]
        public ConstructorStandingType[] ConstructorStanding {
            get {
                return this.constructorStandingField;
            }
            set {
                this.constructorStandingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string season {
            get {
                return this.seasonField;
            }
            set {
                this.seasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string round {
            get {
                return this.roundField;
            }
            set {
                this.roundField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class PitStopType {
        
        private string driverIdField;
        
        private string stopField;
        
        private string lapField;
        
        private System.DateTime timeField;
        
        private bool timeFieldSpecified;
        
        private string durationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string driverId {
            get {
                return this.driverIdField;
            }
            set {
                this.driverIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string stop {
            get {
                return this.stopField;
            }
            set {
                this.stopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string lap {
            get {
                return this.lapField;
            }
            set {
                this.lapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeSpecified {
            get {
                return this.timeFieldSpecified;
            }
            set {
                this.timeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="duration")]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class TimingType {
        
        private string driverIdField;
        
        private string positionField;
        
        private string timeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string driverId {
            get {
                return this.driverIdField;
            }
            set {
                this.driverIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="duration")]
        public string time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class LapType {
        
        private TimingType[] timingField;
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Timing")]
        public TimingType[] Timing {
            get {
                return this.timingField;
            }
            set {
                this.timingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class SpeedType {
        
        private string unitsField;
        
        private float valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public float Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class FastestLapType {
        
        private DurationType timeField;
        
        private SpeedType averageSpeedField;
        
        private string rankField;
        
        private string lapField;
        
        /// <remarks/>
        public DurationType Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        public SpeedType AverageSpeed {
            get {
                return this.averageSpeedField;
            }
            set {
                this.averageSpeedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string rank {
            get {
                return this.rankField;
            }
            set {
                this.rankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string lap {
            get {
                return this.lapField;
            }
            set {
                this.lapField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class DurationType {
        
        private string millisField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string millis {
            get {
                return this.millisField;
            }
            set {
                this.millisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class StatusType {
        
        private string statusIdField;
        
        private string countField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string statusId {
            get {
                return this.statusIdField;
            }
            set {
                this.statusIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class ResultType {
        
        private object[] itemsField;
        
        private object itemField;
        
        private string gridField;
        
        private string lapsField;
        
        private StatusType statusField;
        
        private DurationType timeField;
        
        private FastestLapType fastestLapField;
        
        private string numberField;
        
        private string positionField;
        
        private float pointsField;
        
        private bool pointsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Driver", typeof(DriverType))]
        [System.Xml.Serialization.XmlElementAttribute("DriverIdRef", typeof(string))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Constructor", typeof(ConstructorType))]
        [System.Xml.Serialization.XmlElementAttribute("ConstructorIdRef", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Grid {
            get {
                return this.gridField;
            }
            set {
                this.gridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Laps {
            get {
                return this.lapsField;
            }
            set {
                this.lapsField = value;
            }
        }
        
        /// <remarks/>
        public StatusType Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public DurationType Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        public FastestLapType FastestLap {
            get {
                return this.fastestLapField;
            }
            set {
                this.fastestLapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float points {
            get {
                return this.pointsField;
            }
            set {
                this.pointsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pointsSpecified {
            get {
                return this.pointsFieldSpecified;
            }
            set {
                this.pointsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class QualifyingResultType {
        
        private object itemField;
        
        private object item1Field;
        
        private DurationType q1Field;
        
        private DurationType q2Field;
        
        private DurationType q3Field;
        
        private string numberField;
        
        private string positionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Driver", typeof(DriverType))]
        [System.Xml.Serialization.XmlElementAttribute("DriverIdRef", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Constructor", typeof(ConstructorType))]
        [System.Xml.Serialization.XmlElementAttribute("ConstructorIdRef", typeof(string))]
        public object Item1 {
            get {
                return this.item1Field;
            }
            set {
                this.item1Field = value;
            }
        }
        
        /// <remarks/>
        public DurationType Q1 {
            get {
                return this.q1Field;
            }
            set {
                this.q1Field = value;
            }
        }
        
        /// <remarks/>
        public DurationType Q2 {
            get {
                return this.q2Field;
            }
            set {
                this.q2Field = value;
            }
        }
        
        /// <remarks/>
        public DurationType Q3 {
            get {
                return this.q3Field;
            }
            set {
                this.q3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class LocationType {
        
        private string[] localityField;
        
        private string countryField;
        
        private float latField;
        
        private bool latFieldSpecified;
        
        private float longField;
        
        private bool longFieldSpecified;
        
        private int altField;
        
        private bool altFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Locality")]
        public string[] Locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool latSpecified {
            get {
                return this.latFieldSpecified;
            }
            set {
                this.latFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float @long {
            get {
                return this.longField;
            }
            set {
                this.longField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool longSpecified {
            get {
                return this.longFieldSpecified;
            }
            set {
                this.longFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int alt {
            get {
                return this.altField;
            }
            set {
                this.altField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool altSpecified {
            get {
                return this.altFieldSpecified;
            }
            set {
                this.altFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class CircuitType {
        
        private string circuitNameField;
        
        private LocationType locationField;
        
        private string circuitIdField;
        
        private string urlField;
        
        /// <remarks/>
        public string CircuitName {
            get {
                return this.circuitNameField;
            }
            set {
                this.circuitNameField = value;
            }
        }
        
        /// <remarks/>
        public LocationType Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string circuitId {
            get {
                return this.circuitIdField;
            }
            set {
                this.circuitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class RaceType {
        
        private string raceNameField;
        
        private object itemField;
        
        private System.DateTime dateField;
        
        private System.DateTime timeField;
        
        private QualifyingResultType[] qualifyingListField;
        
        private ResultType[] resultsListField;
        
        private LapType[] lapsListField;
        
        private PitStopType[] pitStopsListField;
        
        private string seasonField;
        
        private string roundField;
        
        private string urlField;
        
        /// <remarks/>
        public string RaceName {
            get {
                return this.raceNameField;
            }
            set {
                this.raceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Circuit", typeof(CircuitType))]
        [System.Xml.Serialization.XmlElementAttribute("CircuitIdRef", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("QualifyingResult", IsNullable=false)]
        public QualifyingResultType[] QualifyingList {
            get {
                return this.qualifyingListField;
            }
            set {
                this.qualifyingListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Result", IsNullable=false)]
        public ResultType[] ResultsList {
            get {
                return this.resultsListField;
            }
            set {
                this.resultsListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Lap", IsNullable=false)]
        public LapType[] LapsList {
            get {
                return this.lapsListField;
            }
            set {
                this.lapsListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PitStop", IsNullable=false)]
        public PitStopType[] PitStopsList {
            get {
                return this.pitStopsListField;
            }
            set {
                this.pitStopsListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string season {
            get {
                return this.seasonField;
            }
            set {
                this.seasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string round {
            get {
                return this.roundField;
            }
            set {
                this.roundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StatusTableType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CircuitTableType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StandingsTableType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConstructorTableType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DriverTableType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RaceTableType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SeasonTableType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public abstract partial class TableType {
        
        private string seasonField;
        
        private string roundField;
        
        private string circuitIdField;
        
        private string constructorIdField;
        
        private string driverIdField;
        
        private string gridField;
        
        private string positionField;
        
        private string statusIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string season {
            get {
                return this.seasonField;
            }
            set {
                this.seasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string round {
            get {
                return this.roundField;
            }
            set {
                this.roundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string circuitId {
            get {
                return this.circuitIdField;
            }
            set {
                this.circuitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string constructorId {
            get {
                return this.constructorIdField;
            }
            set {
                this.constructorIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string driverId {
            get {
                return this.driverIdField;
            }
            set {
                this.driverIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string grid {
            get {
                return this.gridField;
            }
            set {
                this.gridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string statusId {
            get {
                return this.statusIdField;
            }
            set {
                this.statusIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class StatusTableType : TableType {
        
        private StatusType[] statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Status")]
        public StatusType[] Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class CircuitTableType : TableType {
        
        private CircuitType[] circuitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Circuit")]
        public CircuitType[] Circuit {
            get {
                return this.circuitField;
            }
            set {
                this.circuitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class StandingsTableType : TableType {
        
        private StandingsListType[] standingsListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StandingsList")]
        public StandingsListType[] StandingsList {
            get {
                return this.standingsListField;
            }
            set {
                this.standingsListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class ConstructorTableType : TableType {
        
        private ConstructorType[] constructorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Constructor")]
        public ConstructorType[] Constructor {
            get {
                return this.constructorField;
            }
            set {
                this.constructorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class DriverTableType : TableType {
        
        private DriverType[] driverField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Driver")]
        public DriverType[] Driver {
            get {
                return this.driverField;
            }
            set {
                this.driverField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ergast.com/mrd/1.4")]
    public partial class RaceTableType : TableType {
        
        private RaceType[] raceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Race")]
        public RaceType[] Race {
            get {
                return this.raceField;
            }
            set {
                this.raceField = value;
            }
        }
    }
}
